<?php

if (!class_exists('UmbrellaBackupLogCode', false)):
    class UmbrellaBackupLogCode
    {
        const BACKUP_INTEGRITY_SCAN_START = 'BACKUP_INTEGRITY_SCAN_START';
        const BACKUP_INTEGRITY_SCAN_END = 'BACKUP_INTEGRITY_SCAN_END';
        const BACKUP_INTEGRITY_SCAN_SEND_END = 'BACKUP_INTEGRITY_SCAN_SEND_END';
        const BACKUP_SIZE_SCAN_START = 'BACKUP_SIZE_SCAN_START';
        const BACKUP_SIZE_SCAN_END = 'BACKUP_SIZE_SCAN_END';
        const BACKUP_SIZE_SCAN_SEND_END = 'BACKUP_SIZE_SCAN_SEND_END';
        const BACKUP_DIRECTORY_SCAN_START = 'BACKUP_DIRECTORY_SCAN_START';
        const BACKUP_DIRECTORY_SCAN_SEND_END = 'BACKUP_DIRECTORY_SCAN_SEND_END';
        const BACKUP_DIRECTORY_CHECKUP_START = 'BACKUP_DIRECTORY_CHECKUP_START';
        const BACKUP_DIRECTORY_CHECKUP_END = 'BACKUP_DIRECTORY_CHECKUP_END';
        const BACKUP_SEND_FILES_START = 'BACKUP_SEND_FILES_START';
        const BACKUP_SEND_FILES_END = 'BACKUP_SEND_FILES_END';
        const BACKUP_FINISH_SEND = 'BACKUP_FINISH_SEND';
        const BACKUP_SEND_FILES_NO_DICTIONARY = 'BACKUP_SEND_FILES_NO_DICTIONARY';
        const BACKUP_SEND_DATABASE_START = 'BACKUP_SEND_DATABASE_START';
        const BACKUP_SEND_DATABASE_END = 'BACKUP_SEND_DATABASE_END';
        const BACKUP_SEND_DATABASE_SEND_TABLE = 'BACKUP_SEND_DATABASE_SEND_TABLE';

        const BACKUP_MAX_EXECUTION_TIME = 'BACKUP_MAX_EXECUTION_TIME';

        const BACKUP_DATABASE_MAX_EXECUTION_TIME = 'BACKUP_DATABASE_MAX_EXECUTION_TIME';
    }
endif;
